url: "https://www.locolust.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Locolust" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss
  - jekyll-paginate

postcss:
  cache: false

permalink: /:categories/:title

paginate: 5
paginate_path: /page:num/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Julian Lindner"
